### ISSUE TITLE
Uncaught TypeError: this.getTextEditorElement(...).component.onMouseWheel is not a function

### ISSUE THREAD

**Issue by Sirius1897** [mehcode/atom-minimap-plus#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: SIRIUS1897
**Thrown From**: [minimap-plus](https://github.com/mehcode/atom-minimap-plus) package 4.29.1

### Stack Trace

Uncaught TypeError: this.getTextEditorElement(...).component.onMouseWheel is not a function

```
At C:\Users\siriu\.atom\packages\minimap-plus\lib\minimap-element.js:1138

TypeError: this.getTextEditorElement(...).component.onMouseWheel is not a function
    at HTMLElement.relayMousewheelEvent (/packages/minimap-plus/lib/minimap-element.js:1138:45)
    at /packages/minimap-plus/lib/minimap-element.js:492:16)
    at HTMLElement.listener (/packages/minimap-plus/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```

### Commands

```
     -7:21.7.0 core:copy (div.package-detail.panels-item)
  2x -7:10.9.0 core:paste (input.hidden-input)
  6x -6:49.6.0 core:backspace (input.hidden-input)
     -5:48.8.0 core:cut (input.hidden-input)
     -5:47.6.0 core:backspace (input.hidden-input)
     -5:43.5.0 core:paste (input.hidden-input)
  3x -5:09.6.0 core:backspace (input.hidden-input)
     -0:52.8.0 application:open-file (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.12 
minimap-plus 4.29.1 
```

**Comment by Arcanemagus** [comment]
For reference here is the issue filed on `minimap` about the upcoming breakage: https://github.com/atom-minimap/minimap/issues/598

And here is the user reported issue when it wasn't fixed there: https://github.com/atom-minimap/minimap/issues/606

**Comment by mehcode** [comment]
The configuration property `independentMinimapScroll` was also restored to how I believe it should be working. I never saw this when it worked so if I got it wrong, please open an issue.
