### ISSUE TITLE
GitHub should recognize this as a fork

### ISSUE THREAD

**Issue by cbarrick** [mehcode/atom-minimap-plus#3]
This is more of a community issue than a technical one.

It would be nice if GitHub recognized this project as a fork of atom-minimap/minimap. That way it's easier to notice when things change upstream and easier to diff the commit logs. The added transparency gives users an easy way to check if we ever fall behind and by how much.

**Comment by cbarrick** [comment]
I setup such a repo: https://github.com/cbarrick/minimap

1. I used the fork button in the GitHub UI
2. added this repo as a remote
    - `git remote add mehcode https://github.com/mehcode/atom-minimap-plus.git`
3. reset my master to your master
    - `git reset --hard mehcode/master && git push -f`

I'm not sure how to retroactively make GitHub recognize *this* repo as a fork though...

**Comment by mehcode** [comment]
I disagree. Forks can't have issues. And there are forks and then there are _forks_ (such as OpenOffice to LibreOffice), we're more of the later.

I plan to experiment with rewriting the repository for speed and to fix some startup time issues. No idea when I'll get time for that.

If any former contributors wish to come here I'll have them if they pledge to not condone a repeat of what transpired.

**Comment by dkerkow** [comment]
Maybe it would be helpful though to have a notice in the README about this being a fork and why it happened.

**Comment by Arcanemagus** [comment]
@dkerkow The readme already has such a note: https://github.com/mehcode/atom-minimap-plus/commit/8f2623a1115d6cc9d19cd9bd498246571b773c5a.
