### ISSUE TITLE
Is this repo still relevant?

### ISSUE THREAD

**Issue by ansballard** [mehcode/atom-minimap-plus#7]
Just wanted to see if this repo was still being maintained, or if you had switched completely to the original repo. I read through the whole controversy issue, and as far as I can tell you've moved over, so it may be best to put up a visible deprecation notice on here and the apm page. Maybe something like:

# DEPRECATION NOTICE
## This package has been deprecated, as development has moved back to the original per resolution of (link to relevant controversy issue comment here).

Thanks for taking the time to help resolve these issues, keep being awesome!

**Comment by ghost** [comment]
+1, it would be great if this could be clarified. I for one have 0 trust in the previous package and would prefer to use an alternative. Minimap is essentially owned by Kite.

**Comment by mehcode** [comment]
I have full write access to the minimap repository so it's no longer owned solely by Kite. 

I've been letting the dust settle and then I'll update this repository with depreciation notices and take it off apm. You can still install it if you insist by `apm install mehcode/atom-minimap-plus`. I strongly recommend against that as the original repo has several more bug fixes already. 

If needed, I'll fork it again but I have confidence that it won't.

**Comment by ghost** [comment]
Thanks @mehcode, could you briefly explain what exactly are your plans with the original repo? The Kite code will stay there I presume - do you intend to make sure that Kite is not activated without user consent?

**Comment by mehcode** [comment]
@JGH1000 The Kite code is already completely gone and my intent is that it never comes back. If there needs to be minimap integration it can be a plugin.

**Comment by ghost** [comment]
Fantastic, thanks a lot!

**Comment by mscottnelson** [comment]
Thanks for keeping things in line with the parent repo @mehcode. Still disturbed by the Kite incident.
